package ru.tensor.sbis.formatter.dateTime

/**
 * Форматы даты и времени для форматера, в зависимости от региона.
 *
 * @author ps.smirnyh
 */
internal object DateTimeFormats {

    private val ru_formats = mapOf(
        "DIGITAL_MONTH_FULL_YEAR" to "MM.YYYY",
        "FULL_DATE_DOW" to "d MMMM''YY, EEEE",
        "DAY" to "d",
        "FULL_DATE" to "dd.MM.YY",
        "FULL_DATE_FULL_MONTH" to "d MMMM''YY",
        "FULL_DATE_FULL_MONTH_FULL_YEAR" to "d MMMM YYYY",
        "FULL_DATE_FULL_YEAR" to "dd.MM.YYYY",
        "FULL_DATE_SHORT_MONTH" to "d MMM''YY",
        "FULL_DATE_SHORT_MONTH_FULL_YEAR" to "d MMM YYYY",
        "FULL_DATE_SHORT_TIME" to "dd.MM.YY HH:mm",
        "FULL_DATE_FULL_TIME" to "dd.MM.YY HH:mm:ss",
        "FULL_DATE_FULL_TIME_FRACTION" to "dd.MM.YY HH:mm:ss.SSS",
        "FULL_DATE_FULL_YEAR_SHORT_TIME" to "dd.MM.YYYY HH:mm",
        "FULL_DATE_FULL_YEAR_FULL_TIME" to "dd.MM.YYYY HH:mm:ss",
        "FULL_DATE_FULL_YEAR_FULL_TIME_FRACTION" to "dd.MM.YYYY HH:mm:ss.SSS",
        "FULL_DATETIME" to "d MMM''YY HH:mm",
        "FULL_MONTH" to "MMMM''YY",
        "MONTH" to "MMMM",
        "SHR_MONTH" to "MMM",
        "FULL_QUARTER" to "QQQQ''YY",
        "QUARTER" to "Q",
        "FULL_YEAR" to "YYYY",
        "FULL_TIME" to "HH:mm:ss",
        "FULL_TIME_FRACTION" to "HH:mm:ss.SSS",
        "ISO_DATETIME" to "YYYY-MM-dd'T'HH:mm:ss.SSSZZ",
        "ISO_DATETIME_SQL" to "YYYY-MM-dd HH:mm:ss.SSSZZ",
        "SHORT_DATE_DOW" to "d MMMM, EEEE",
        "SHORT_DATE_SHORT_DOW" to "d MMMM, EE",
        "SHORT_DATE_SHORT_MONTH_SHORT_DOW" to "d MMM, EE",
        "SHORT_DATE" to "dd.MM",
        "SHORT_DATE_FULL_MONTH" to "d MMMM",
        "SHORT_DATE_SHORT_MONTH" to "d MMM",
        "SHORT_DATE_SHORT_TIME" to "dd.MM HH:mm",
        "SHORT_DATE_FULL_TIME" to "dd.MM HH:mm:ss",
        "SHORT_DATE_FULL_TIME_FRACTION" to "dd.MM HH:mm:ss.SSS",
        "SHORT_DATETIME" to "d MMM HH:mm",
        "SHORT_MONTH" to "MMM''YY",
        "SHORT_QUARTER" to "QQ''YY",
        "SHORT_TIME" to "HH:mm"
    )

    private val kz_formats = mapOf(
        "DIGITAL_MONTH_FULL_YEAR" to "MM.YYYY",
        "FULL_DATE_DOW" to "d MMMM''YY, EEEE",
        "DAY" to "d",
        "FULL_DATE" to "dd.MM.YY",
        "FULL_DATE_FULL_MONTH" to "d MMMM''YY",
        "FULL_DATE_FULL_MONTH_FULL_YEAR" to "d MMMM YYYY",
        "FULL_DATE_FULL_YEAR" to "dd.MM.YYYY",
        "FULL_DATE_SHORT_MONTH" to "d MMM''YY",
        "FULL_DATE_SHORT_MONTH_FULL_YEAR" to "d MMM YYYY",
        "FULL_DATE_SHORT_TIME" to "dd.MM.YY HH:mm",
        "FULL_DATE_FULL_TIME" to "dd.MM.YY HH:mm:ss",
        "FULL_DATE_FULL_TIME_FRACTION" to "dd.MM.YY HH:mm:ss.SSS",
        "FULL_DATE_FULL_YEAR_SHORT_TIME" to "dd.MM.YYYY HH:mm",
        "FULL_DATE_FULL_YEAR_FULL_TIME" to "dd.MM.YYYY HH:mm:ss",
        "FULL_DATE_FULL_YEAR_FULL_TIME_FRACTION" to "dd.MM.YYYY HH:mm:ss.SSS",
        "FULL_DATETIME" to "d MMM''YY HH:mm",
        "FULL_MONTH" to "MMMM''YY",
        "MONTH" to "MMMM",
        "SHR_MONTH" to "MMM",
        "FULL_QUARTER" to "QQQQ''YY",
        "QUARTER" to "Q",
        "FULL_YEAR" to "YYYY",
        "FULL_TIME" to "HH:mm:ss",
        "FULL_TIME_FRACTION" to "HH:mm:ss.SSS",
        "ISO_DATETIME" to "YYYY-MM-ddTHH:mm:ss.SSSZZ",
        "ISO_DATETIME_SQL" to "YYYY-MM-dd HH:mm:ss.SSSZZ",
        "SHORT_DATE_DOW" to "d MMMM, EEEE",
        "SHORT_DATE_SHORT_DOW" to "d MMMM, EE",
        "SHORT_DATE_SHORT_MONTH_SHORT_DOW" to "d MMM, EE",
        "SHORT_DATE" to "dd.MM",
        "SHORT_DATE_FULL_MONTH" to "d MMMM",
        "SHORT_DATE_SHORT_MONTH" to "d MMM",
        "SHORT_DATE_SHORT_TIME" to "dd.MM HH:mm",
        "SHORT_DATE_FULL_TIME" to "dd.MM HH:mm:ss",
        "SHORT_DATE_FULL_TIME_FRACTION" to "dd.MM HH:mm:ss.SSS",
        "SHORT_DATETIME" to "d MMM HH:mm",
        "SHORT_MONTH" to "MMM''YY",
        "SHORT_QUARTER" to "QQ''YY",
        "SHORT_TIME" to "HH:mm"
    )

    private val us_formats = mapOf(
        "DIGITAL_MONTH_FULL_YEAR" to "MM/dd/YYYY",
        "FULL_DATE_DOW" to "EEEE, MMMM d''YY",
        "DAY" to "d",
        "FULL_DATE" to "MM/dd/YY",
        "FULL_DATE_FULL_MONTH" to "MMMM d''YY",
        "FULL_DATE_FULL_MONTH_FULL_YEAR" to "MMMM d, YYYY",
        "FULL_DATE_FULL_YEAR" to "MM/dd/YYYY",
        "FULL_DATE_SHORT_MONTH" to "MMM d''YY",
        "FULL_DATE_SHORT_MONTH_FULL_YEAR" to "MMM d, YYYY",
        "FULL_DATE_SHORT_TIME" to "MM/dd/YY HH:mm",
        "FULL_DATE_FULL_TIME" to "MM/dd/YY HH:mm:ss",
        "FULL_DATE_FULL_TIME_FRACTION" to "MM/dd/YY HH:mm:ss.SSS",
        "FULL_DATE_FULL_YEAR_SHORT_TIME" to "MM/dd/YYYY HH:mm",
        "FULL_DATE_FULL_YEAR_FULL_TIME" to "MM/dd/YYYY HH:mm:ss",
        "FULL_DATE_FULL_YEAR_FULL_TIME_FRACTION" to "MM/dd/YYYY HH:mm:ss.SSS",
        "FULL_DATETIME" to "MMM d''YY HH:mm",
        "FULL_MONTH" to "MMMM''YY",
        "MONTH" to "MMMM",
        "SHR_MONTH" to "MMM",
        "FULL_QUARTER" to "QQQQ''YY",
        "QUARTER" to "Q",
        "FULL_YEAR" to "YYYY",
        "FULL_TIME" to "HH:mm:ss",
        "FULL_TIME_FRACTION" to "HH:mm:ss.SSS",
        "ISO_DATETIME" to "YYYY-MM-dd'T'HH:mm:ss.SSSZZ",
        "ISO_DATETIME_SQL" to "YYYY-MM-dd HH:mm:ss.SSSZZ",
        "SHORT_DATE_DOW" to "EEEE, MMMM d",
        "SHORT_DATE_SHORT_DOW" to "EE, MMMM d",
        "SHORT_DATE_SHORT_MONTH_SHORT_DOW" to "EE, MMM d",
        "SHORT_DATE" to "MM/dd",
        "SHORT_DATE_FULL_MONTH" to "d MMMM",
        "SHORT_DATE_SHORT_MONTH" to "d MMM",
        "SHORT_DATE_SHORT_TIME" to "MM/dd HH:mm",
        "SHORT_DATE_FULL_TIME" to "MM/dd HH:mm:ss",
        "SHORT_DATE_FULL_TIME_FRACTION" to "MM/dd HH:mm:ss.SSS",
        "SHORT_DATETIME" to "d MMM HH:mm",
        "SHORT_MONTH" to "MMM''YY",
        "SHORT_QUARTER" to "QQQ''YY",
        "SHORT_TIME" to "HH:mm"
    )

    private val uz_formats = mapOf(
        "DIGITAL_MONTH_FULL_YEAR" to "MM.YYYY",
        "FULL_DATE_DOW" to "d MMMM''YY, EEEE",
        "DAY" to "d",
        "FULL_DATE" to "dd.MM.YY",
        "FULL_DATE_FULL_MONTH" to "d MMMM''YY",
        "FULL_DATE_FULL_MONTH_FULL_YEAR" to "d MMMM YYYY",
        "FULL_DATE_FULL_YEAR" to "dd.MM.YYYY",
        "FULL_DATE_SHORT_MONTH" to "d MMM''YY",
        "FULL_DATE_SHORT_MONTH_FULL_YEAR" to "d MMM YYYY",
        "FULL_DATE_SHORT_TIME" to "dd.MM.YY HH:mm",
        "FULL_DATE_FULL_TIME" to "dd.MM.YY HH:mm:ss",
        "FULL_DATE_FULL_TIME_FRACTION" to "dd.MM.YY HH:mm:ss.SSS",
        "FULL_DATE_FULL_YEAR_SHORT_TIME" to "dd.MM.YYYY HH:mm",
        "FULL_DATE_FULL_YEAR_FULL_TIME" to "dd.MM.YYYY HH:mm:ss",
        "FULL_DATE_FULL_YEAR_FULL_TIME_FRACTION" to "dd.MM.YYYY HH:mm:ss.SSS",
        "FULL_DATETIME" to "d MMM''YY HH:mm",
        "FULL_MONTH" to "MMMM''YY",
        "MONTH" to "MMMM",
        "SHR_MONTH" to "MMM",
        "FULL_QUARTER" to "QQQQ''YY",
        "QUARTER" to "Q",
        "FULL_YEAR" to "YYYY",
        "FULL_TIME" to "HH:mm:ss",
        "FULL_TIME_FRACTION" to "HH:mm:ss.SSS",
        "ISO_DATETIME" to "YYYY-MM-ddTHH:mm:ss.SSSZZ",
        "ISO_DATETIME_SQL" to "YYYY-MM-dd HH:mm:ss.SSSZZ",
        "SHORT_DATE_DOW" to "d MMMM, EEEE",
        "SHORT_DATE_SHORT_DOW" to "d MMMM, EE",
        "SHORT_DATE_SHORT_MONTH_SHORT_DOW" to "d MMM, EE",
        "SHORT_DATE" to "dd.MM",
        "SHORT_DATE_FULL_MONTH" to "d MMMM",
        "SHORT_DATE_SHORT_MONTH" to "d MMM",
        "SHORT_DATE_SHORT_TIME" to "dd.MM HH:mm",
        "SHORT_DATE_FULL_TIME" to "dd.MM HH:mm:ss",
        "SHORT_DATE_FULL_TIME_FRACTION" to "dd.MM HH:mm:ss.SSS",
        "SHORT_DATETIME" to "d MMM HH:mm",
        "SHORT_MONTH" to "MMM''YY",
        "SHORT_QUARTER" to "QQ''YY",
        "SHORT_TIME" to "HH:mm"
    )

    /** @SelfDocumented */
    val formats = mapOf(
        "RU" to ru_formats,
        "KZ" to kz_formats,
        "US" to us_formats,
        "UZ" to uz_formats
    )
}