/*
 * Copyright 2014 Mike Penz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.tensor.sbis.design;

import android.content.Context;
import android.graphics.Typeface;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.mikepenz.iconics.typeface.IIcon;
import com.mikepenz.iconics.typeface.ITypeface;

import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

import timber.log.Timber;

/**
 * Класс для работы с файлом шрифта 'cbuc_icons'.
 *
 * @author vv.chekurda
 */
@SuppressWarnings("JavaDoc")
public class CbucIcon implements ITypeface {
    private static Typeface typeface = null;
    private static HashMap<String, Character> mChars;

    @Override
    public IIcon getIcon(String key) {
        return Icon.valueOf(key);
    }

    @Override
    public HashMap<String, Character> getCharacters() {
        if (mChars == null) {
            HashMap<String, Character> aChars = new HashMap<>();
            for (Icon v : Icon.values()) {
                aChars.put(v.name(), v.character);
            }
            mChars = aChars;
        }
        return mChars;
    }

    @Override
    public String getMappingPrefix() {
        return "cbi";
    }

    @Override
    public String getFontName() {
        return "Cbuc Icon";
    }

    @Override
    public String getVersion() {
        return "";
    }

    @Override
    public int getIconCount() {
        return mChars.size();
    }

    @Override
    public Collection<String> getIcons() {
        Collection<String> icons = new LinkedList<>();
        for (Icon value : Icon.values()) {
            icons.add(value.name());
        }
        return icons;
    }

    @Override
    public String getAuthor() {
        return "";
    }

    @Override
    public String getUrl() {
        return "";
    }

    @Override
    public String getDescription() {
        return "";
    }

    @Override
    public String getLicense() {
        return "";
    }

    @Override
    public String getLicenseUrl() {
        return "";
    }

    @Override
    public Typeface getTypeface(Context context) {
        if (typeface == null) {
            try {
                typeface = TypefaceManager.getCbucIconTypeface(context);
            } catch (Exception e) {
                return null;
            }
        }
        return typeface;
    }

    /**
     * Набор иконок шрифта 'cbuc_icons'.
     * <p>
     * FYI: Последняя добавленная версия шрифта (16) - 1_12_150.
     */
    public enum Icon implements IIcon {
		cbi_1CBitrix('\ueaf4'),
		cbi_1c('\ue71f'),
		cbi_AccordionArrowDown('\ue9d7'),
		cbi_AccordionArrowUp('\ue9d8'),
		cbi_Actor('\ueb29'),
		cbi_Add('\ue677'),
		cbi_AddButton('\ue694'),
		cbi_AddButtonNew('\ue95d'),
		cbi_AddContact('\ueb6b'),
		cbi_AddForSectoinOfAccordion('\ueb25'),
		cbi_AddHost('\ueafc'),
		cbi_AddMapMarker('\ueacd'),
		cbi_AddNote('\ue76e'),
		cbi_Addition('\ueae9'),
		cbi_AdditionalConditions('\ue72b'),
		cbi_Admin('\ue676'),
		cbi_Admin2('\ue760'),
		cbi_Admin2off('\ue906'),
		cbi_AdminInfo('\uea4a'),
		cbi_AdvertisingArrow('\uea5d'),
		cbi_Agent('\uea43'),
		cbi_Agreed('\uea26'),
		cbi_Album('\ue90a'),
		cbi_Alert('\ue675'),
		cbi_AlignmentBottom('\ue6ef'),
		cbi_AlignmentCenter('\ue6bf'),
		cbi_AlignmentLeft('\ue6c0'),
		cbi_AlignmentMiddle('\ue6f0'),
		cbi_AlignmentRight('\ue6c1'),
		cbi_AlignmentTop('\ue6f1'),
		cbi_AlignmentWidth('\ue6c2'),
		cbi_AlignmentWidth2('\ue9fb'),
		cbi_AmoCrm('\ueb1f'),
		cbi_And('\ue9ef'),
		cbi_Android('\ue769'),
		cbi_Annul('\ueac2'),
		cbi_AnotherSignatureCenter('\ue674'),
		cbi_Answers('\ue9ec'),
		cbi_Antiseptic('\ueb7f'),
		cbi_ApplyChangesL('\ueaf0'),
		cbi_ApplyChangesR('\ueaef'),
		cbi_Arbitrarily('\ueaae'),
		cbi_Archive('\ue6ec'),
		cbi_AreaBlur('\ueade'),
		cbi_AreaGeom('\ueb28'),
		cbi_ArrangeColumns('\ue6da'),
		cbi_ArrangeLargeIcons1('\ue6db'),
		cbi_ArrangeLargeIcons2('\ue6dc'),
		cbi_ArrangeList('\ue708'),
		cbi_ArrangeList03('\ue995'),
		cbi_ArrangeList04('\ue994'),
		cbi_ArrangeList1('\ue6dd'),
		cbi_ArrangeList2('\ue6de'),
		cbi_ArrangeList3('\ue9c8'),
		cbi_ArrangePreview('\ue6df'),
		cbi_ArrangeSmallIconsPreview('\ue720'),
		cbi_Arrow1730('\ue692'),
		cbi_Arrow1730Null('\ue715'),
		cbi_ArrowBig('\ue9f3'),
		cbi_ArrowDown('\ue673'),
		cbi_ArrowDownNull('\ue716'),
		cbi_ArrowTimeBackward('\ue9d6'),
		cbi_ArrowTimeForward('\ue9d5'),
		cbi_ArrowUp('\ue672'),
		cbi_ArrowUpNull('\ue717'),
		cbi_Asterisk('\ueae0'),
		cbi_Attach('\ue671'),
		cbi_AttentionProcessing('\uea55'),
		cbi_Author('\ue6f2'),
		cbi_AutoIndent('\ue9e3'),
		cbi_AutoIndent2('\ueac1'),
		cbi_AutoTuning('\ue9fa'),
		cbi_Autonomcash('\uea2b'),
		cbi_Avito('\ueafd'),
		cbi_Back('\ue69c'),
		cbi_Back2('\ue97f'),
		cbi_BackArrow('\ueaf7'),
		cbi_BadToGood('\ue670'),
		cbi_Badge('\uea4c'),
		cbi_Badges('\ueb4d'),
		cbi_Bank('\uea93'),
		cbi_Barcode('\ue925'),
		cbi_Barcode2('\uea99'),
		cbi_BarcodeNon('\uea81'),
		cbi_Bell('\ue69b'),
		cbi_BellCross('\ueb4e'),
		cbi_BidUp('\ue97b'),
		cbi_Bids('\ue68c'),
		cbi_BigRemark('\ue9ea'),
		cbi_BigRemarkNull('\ue9f2'),
		cbi_Bike('\ueafe'),
		cbi_Bill('\ue66f'),
		cbi_Birthday('\ue6a4'),
		cbi_Bold('\ue6c3'),
		cbi_Bonus('\ueb57'),
		cbi_Boolean('\ueab0'),
		cbi_Bottle('\ueb4f'),
		cbi_BtArrow('\ueb60'),
		cbi_Bug('\uea92'),
		cbi_Bulb('\uea05'),
		cbi_Burger('\uea90'),
		cbi_Button('\ueb7e'),
		cbi_CZN('\ueb2d'),
		cbi_Calc('\ue981'),
		cbi_Calendar('\ue6c4'),
		cbi_Calendar2('\ue75f'),
		cbi_Call('\ueadf'),
		cbi_CallGroup('\uead5'),
		cbi_CallIncoming('\ue68e'),
		cbi_CallOutgoing('\ue65f'),
		cbi_CallSaby('\ue99f'),
		cbi_Cameras('\ueaff'),
		cbi_CapitalInvestment('\ue74b'),
		cbi_CarryDiscount('\ue9bb'),
		cbi_Cashbox('\ue9cf'),
		cbi_Cashbox2('\uea3c'),
		cbi_CashboxNon('\ueab6'),
		cbi_Catalog('\uea9a'),
		cbi_Cause('\uea59'),
		cbi_CbPlus('\ue959'),
		cbi_Celebration('\uea57'),
		cbi_Champagne('\uea2c'),
		cbi_ChangeAccount('\ue916'),
		cbi_ChangeSize('\ueb2b'),
		cbi_Chat('\ue90f'),
		cbi_Check('\ue66e'),
		cbi_Check2('\ue644'),
		cbi_Check3('\ue76f'),
		cbi_CheckDoc('\ue66d'),
		cbi_Checkreport('\ueb5e'),
		cbi_Chest('\ue76b'),
		cbi_CircleGeom('\ueb2c'),
		cbi_Classifications('\ue918'),
		cbi_Client('\uea44'),
		cbi_Client2('\uea9b'),
		cbi_ClientChat('\ueb80'),
		cbi_Clients('\uea9c'),
		cbi_Close('\ue66c'),
		cbi_CloseCheck('\ueb8e'),
		cbi_CloseNew('\uea27'),
		cbi_Cloud('\ueb84'),
		cbi_CloudControl('\ue9f4'),
		cbi_CloudKey2('\ue9b0'),
		cbi_CloudKey2None('\ue9af'),
		cbi_CloudOff('\ueb7a'),
		cbi_CloudUser('\ue9f9'),
		cbi_CollapseExpand('\uea2f'),
		cbi_CollapseLight('\ue9a8'),
		cbi_Colorize('\ue664'),
		cbi_ColorizeNone('\ue907'),
		cbi_Column1('\ue9c7'),
		cbi_Column2('\ue9c6'),
		cbi_CommaSign('\ueadc'),
		cbi_CommercialSignature('\ue66b'),
		cbi_Company('\ue66a'),
		cbi_Company2('\ue91e'),
		cbi_Compare('\uea3d'),
		cbi_ConnectionPeriod('\ue9eb'),
		cbi_ConnectionPeriodNon('\uea94'),
		cbi_ContactSearch('\ue704'),
		cbi_Contrast('\ue9a4'),
		cbi_Copy('\ue669'),
		cbi_CopyPhoto('\ueac4'),
		cbi_Courses('\ueb7b'),
		cbi_CreateFolder('\ue668'),
		cbi_CreateFolder2('\ueb61'),
		cbi_Crop('\ue6e0'),
		cbi_CropPic('\uea1d'),
		cbi_Crown('\ue9ee'),
		cbi_CrownFill('\ueb38'),
		cbi_CrownNull('\ueaba'),
		cbi_CrownOff('\ueabe'),
		cbi_Curtail('\ue67b'),
		cbi_CurtailList('\ue658'),
		cbi_CurtailMessage('\ue6f3'),
		cbi_Cutlery('\uea1f'),
		cbi_DK('\ue691'),
		cbi_DKEng('\ue9e0'),
		cbi_DKNone('\ue640'),
		cbi_DKNoneEng('\ue9de'),
		cbi_DayBackward('\ue667'),
		cbi_DayBackwardNull('\ue718'),
		cbi_DayForward('\ue666'),
		cbi_DayForwardBsLine('\ue770'),
		cbi_DayForwardNull('\ue719'),
		cbi_Decline('\ue665'),
		cbi_Degradation('\ue94d'),
		cbi_Delete('\ue663'),
		cbi_Delete02('\ue92a'),
		cbi_DeliveryClub('\ueb58'),
		cbi_DemonstrationScreen('\uead0'),
		cbi_Desktop('\ue90d'),
		cbi_DesktopComplete('\ue90b'),
		cbi_DesktopOff('\ue917'),
		cbi_DetailList('\ue71a'),
		cbi_Detailed('\ueb49'),
		cbi_Directory('\ue919'),
		cbi_Discount('\ue703'),
		cbi_Discount2('\uea9d'),
		cbi_DiscountCard('\ue71b'),
		cbi_DiscountCardSale('\ue98e'),
		cbi_Discrepancies('\ueb21'),
		cbi_Division('\ueae6'),
		cbi_DkOff('\ue800'),
		cbi_Docsvision('\uea23'),
		cbi_Document('\ue661'),
		cbi_DocumentBase('\ue967'),
		cbi_DocumentBaseNull('\ueb59'),
		cbi_DocumentNo('\ueb51'),
		cbi_DocumentP('\ue6ff'),
		cbi_DocumentTerm('\ue67a'),
		cbi_DocumentUnknownType('\ue700'),
		cbi_DocumentW('\ue6e1'),
		cbi_DocumentX('\ue6e2'),
		cbi_DocumentXml('\ue6e3'),
		cbi_DocumentXmlEdit('\ue900'),
		cbi_DocumentZip('\ue6e4'),
		cbi_Dollar('\ue6d6'),
		cbi_Down('\ue996'),
		cbi_DownloadNew('\uea30'),
		cbi_Drop('\uea51'),
		cbi_Dwg('\uea36'),
		cbi_Edit('\ue660'),
		cbi_EditComment('\ue60d'),
		cbi_Edo('\ue679'),
		cbi_Edo2('\ue689'),
		cbi_Egais('\ue905'),
		cbi_Email('\ue65e'),
		cbi_EmailMark('\uea89'),
		cbi_EmailNew('\uea32'),
		cbi_Eml('\ueaad'),
		cbi_EmoiconAngry('\ue6a9'),
		cbi_EmoiconAngryInvert('\ue92d'),
		cbi_EmoiconAnnoyed('\ue6aa'),
		cbi_EmoiconBlind('\ue6ab'),
		cbi_EmoiconCool('\ue6ac'),
		cbi_EmoiconCry('\ue6ad'),
		cbi_EmoiconDevil('\ue6ae'),
		cbi_EmoiconDumb('\ue6af'),
		cbi_EmoiconFacepalm('\ue926'),
		cbi_EmoiconInlove('\ue6b0'),
		cbi_EmoiconKiss('\ue6b1'),
		cbi_EmoiconLaugh('\ue6b2'),
		cbi_EmoiconLaughInvert('\ue92f'),
		cbi_EmoiconMoney('\ue6b3'),
		cbi_EmoiconNerd('\ue6b4'),
		cbi_EmoiconNeutral('\ue6b5'),
		cbi_EmoiconPuzzled('\ue6b6'),
		cbi_EmoiconRofl('\ue6b7'),
		cbi_EmoiconSad('\ue6b8'),
		cbi_EmoiconShocked('\ue6b9'),
		cbi_EmoiconShockedInvert('\ue92e'),
		cbi_EmoiconSmile('\ue6ba'),
		cbi_EmoiconSnooze('\ue6bb'),
		cbi_EmoiconTongue('\ue6bc'),
		cbi_EmoiconWink('\ue6bd'),
		cbi_EmoiconYawn('\ue6be'),
		cbi_EmptyFolderClosed('\ue96c'),
		cbi_EmptyFolderOpen('\ue96b'),
		cbi_EmptyMessage('\ue65d'),
		cbi_EmptyVideoMessage('\ue6fb'),
		cbi_Enter('\ue927'),
		cbi_EnterRight('\uea04'),
		cbi_Eo('\ue688'),
		cbi_Eo2('\ue687'),
		cbi_Equally('\ueae8'),
		cbi_Erase('\ue65c'),
		cbi_Erase1('\ueaeb'),
		cbi_Eraser('\ueaca'),
		cbi_Euro('\ue6d7'),
		cbi_Examined('\ue946'),
		cbi_Exclamation('\ue65b'),
		cbi_ExclamationCircle('\ueb56'),
		cbi_ExclamationNarrow('\uea67'),
		cbi_Executor('\ueaf8'),
		cbi_ExitAccount('\uea16'),
		cbi_ExitMan('\ueb88'),
		cbi_Expand('\ue686'),
		cbi_ExpandDown('\ue802'),
		cbi_ExpandLight('\ue9aa'),
		cbi_ExpandList('\ue67d'),
		cbi_ExpandMessage('\ue6f4'),
		cbi_ExpandTable('\ueb62'),
		cbi_ExpandUp('\ue801'),
		cbi_FNS('\ueb2e'),
		cbi_FSRAR('\ueb2f'),
		cbi_FSS('\ueb30'),
		cbi_Favorite('\ue65a'),
		cbi_FavoriteHalf('\ueb44'),
		cbi_FileAccess('\ueb6d'),
		cbi_Fill('\ue659'),
		cbi_FillintheInformation('\uea0f'),
		cbi_Filter('\ue64f'),
		cbi_FilterBig('\uea2d'),
		cbi_FilterNew('\ue94c'),
		cbi_FilterSmall('\ue9ac'),
		cbi_Finger('\uea4d'),
		cbi_Fire('\ue657'),
		cbi_First('\ue980'),
		cbi_Flag('\ue656'),
		cbi_Folder('\ue655'),
		cbi_FolderClosed('\ue96e'),
		cbi_FolderIOS('\ue99a'),
		cbi_FolderOpen('\ue96d'),
		cbi_Footwear('\ueb00'),
		cbi_Forward('\ue97e'),
		cbi_ForwardBaseLine('\ueac5'),
		cbi_FromArchive('\ue69d'),
		cbi_FullScrin('\ue95f'),
		cbi_FurCoat('\ueb01'),
		cbi_Fx('\ue9f1'),
		cbi_GIF('\ueb1b'),
		cbi_GeoCluster('\ue947'),
		cbi_GeoMarker('\ue948'),
		cbi_Gif2('\ueb42'),
		cbi_Gift('\ueb7c'),
		cbi_Gmail('\uea3b'),
		cbi_GoTo('\ueb1c'),
		cbi_GooglePlus('\ue763'),
		cbi_Group('\ue92b'),
		cbi_GroupTabsDown('\ue9e6'),
		cbi_GroupTabsLeft('\ue9e4'),
		cbi_GroupTabsRight('\ue9e5'),
		cbi_GroupTabsUp('\ue9e7'),
		cbi_Groups('\ue654'),
		cbi_HHNon('\uea14'),
		cbi_Hand('\ue721'),
		cbi_Handshake('\uea7f'),
		cbi_Handwrite1('\ue653'),
		cbi_Handwrite2('\ue652'),
		cbi_HangUp('\ueb52'),
		cbi_HardDrive('\ue705'),
		cbi_HashSign('\ueae4'),
		cbi_HeadHunter('\ue9ae'),
		cbi_HeaderBottom('\ue922'),
		cbi_HeaderTop('\ue923'),
		cbi_Headstone('\ue76c'),
		cbi_Hide('\ue651'),
		cbi_HierarchyView('\ue650'),
		cbi_Home('\ue64e'),
		cbi_Home2('\ue64c'),
		cbi_Home3('\ue920'),
		cbi_Home3BsLine('\ueac6'),
		cbi_Html('\ue6c5'),
		cbi_IPmask('\ue64a'),
		cbi_Icq('\ue64d'),
		cbi_Iiko('\ueaf3'),
		cbi_InGroup('\ue99e'),
		cbi_InSales('\ueaf2'),
		cbi_IncomingCall('\uea60'),
		cbi_IncomingCallNull('\uea8c'),
		cbi_IncomingMail('\uea64'),
		cbi_Info('\ue64b'),
		cbi_InputHistory('\ue6a8'),
		cbi_InsertCode('\uea88'),
		cbi_InsertSpoiler('\uea47'),
		cbi_InsideBorders('\ueaf5'),
		cbi_Instagram('\uea56'),
		cbi_InstagramLine('\ueb3b'),
		cbi_IntangibleAssets('\ue74c'),
		cbi_InternationalArrow('\uea5c'),
		cbi_Interview('\ue9a6'),
		cbi_Invoice('\ue9f5'),
		cbi_Italic('\ue6c6'),
		cbi_KPI('\ueb82'),
		cbi_Kanban('\ueb8d'),
		cbi_Key('\ue9c5'),
		cbi_KnowledgeBase('\ueb81'),
		cbi_LDAPnew('\uea50'),
		cbi_Last('\ue97d'),
		cbi_Ldap('\uea11'),
		cbi_Lead('\ue6f5'),
		cbi_Lenta('\ueb45'),
		cbi_LessButton('\ue6d4'),
		cbi_LetterA('\ue678'),
		cbi_LetterN('\ue979'),
		cbi_LetterNull('\ueab8'),
		cbi_LetterP('\ueabb'),
		cbi_LetterY('\ueabc'),
		cbi_LevelAverage('\uea73'),
		cbi_LevelCritical('\uea75'),
		cbi_LevelHigh('\uea74'),
		cbi_LevelLow('\uea72'),
		cbi_LightIndustry('\ueb02'),
		cbi_Lightning('\uea0b'),
		cbi_Line('\ue999'),
		cbi_Link('\ue6a7'),
		cbi_Linked('\ue649'),
		cbi_ListMarked('\ue6c7'),
		cbi_ListNumbered('\ue6c8'),
		cbi_ListView('\ue648'),
		cbi_ListViewNew('\uea28'),
		cbi_Listbox('\ue6d8'),
		cbi_ListboxNull('\uea3a'),
		cbi_ListboxrRflection('\ue9db'),
		cbi_Location('\ueb31'),
		cbi_Lock('\ue647'),
		cbi_LockIn('\uea1b'),
		cbi_LockOK('\ue95c'),
		cbi_LogoFacebook('\ue722'),
		cbi_LogoGosUslugi('\uea0e'),
		cbi_LogoLinkedIn('\ue723'),
		cbi_LogoMoiKrug('\ue724'),
		cbi_LogoMoiMir('\ue725'),
		cbi_LogoOk('\ue728'),
		cbi_LogoTelegram('\ueb3a'),
		cbi_LogoTwitter('\ue726'),
		cbi_LogoVk('\ue727'),
		cbi_LongList('\ue961'),
		cbi_Love('\uea83'),
		cbi_LoveNull('\uea82'),
		cbi_Lunch('\ueb87'),
		cbi_MP4('\ueb1d'),
		cbi_MVD('\ueb32'),
		cbi_MagicWand('\ue998'),
		cbi_Mail('\ue646'),
		cbi_MailIncoming('\ue6e5'),
		cbi_MailLetter('\ueace'),
		cbi_MailOutgoing('\ue6e6'),
		cbi_ManyDocuments('\uea39'),
		cbi_Map('\ue645'),
		cbi_MapMarker('\ue928'),
		cbi_MapMarkerBig('\uea95'),
		cbi_MapMarkerNull('\uea52'),
		cbi_MarkCLeftLight('\ue9a9'),
		cbi_MarkCRightLight('\ue9ab'),
		cbi_MarkCollapseBold('\ue9bf'),
		cbi_MarkExpandBold('\ue9c1'),
		cbi_MarkExpandBoldMin('\ueb8a'),
		cbi_MarkLeftBold('\ue9c0'),
		cbi_MarkRightBold('\ue9c2'),
		cbi_MarkRightBoldMin('\ueb89'),
		cbi_Marking('\ueaf6'),
		cbi_Master('\ue643'),
		cbi_MedicalCase('\ue72d'),
		cbi_Medicines('\ueb03'),
		cbi_Megaphone('\ue69a'),
		cbi_MegaphoneMan('\ue699'),
		cbi_MegaphoneNull('\ue95a'),
		cbi_MegaphoneOff('\ue99b'),
		cbi_Megaplan('\ueb20'),
		cbi_MenuAk('\uea98'),
		cbi_Mercury('\uea34'),
		cbi_MergeCells('\ueb0d'),
		cbi_Message2('\ue642'),
		cbi_Microphone('\ue706'),
		cbi_Microphone1('\ueae1'),
		cbi_MicrophoneNull('\ue9b1'),
		cbi_MicrophoneOff('\ue90c'),
		cbi_MilkProducts('\ueb04'),
		cbi_Minus('\ueb6e'),
		cbi_MixPayment('\uea0d'),
		cbi_MixPayment1('\uea9f'),
		cbi_MixPaymentButton('\uea9e'),
		cbi_Money('\ue641'),
		cbi_MoneyOk('\ue95b'),
		cbi_MoneyPrice('\uea38'),
		cbi_MoreButton('\ue6d5'),
		cbi_Motion('\ue96f'),
		cbi_Move('\ue63f'),
		cbi_Move2('\ue63e'),
		cbi_MoveCellAbove('\ueb17'),
		cbi_MoveCellBelow('\ueb18'),
		cbi_MoveCellLeft('\ueb19'),
		cbi_MoveCellRight('\ueb1a'),
		cbi_MoveTableCell('\ueb16'),
		cbi_Multiplication('\ueaec'),
		cbi_NewCategory('\ue63d'),
		cbi_NewSmile('\ueb6f'),
		cbi_NewTab('\ue63c'),
		cbi_News('\ueb33'),
		cbi_Next('\ue6d9'),
		cbi_NoDocument('\ue991'),
		cbi_NoMoney('\uea35'),
		cbi_NoPlan('\ueb63'),
		cbi_NodeCurtailed('\ue6d3'),
		cbi_NodeExpanded('\ue6d2'),
		cbi_NotForPrint('\ueb39'),
		cbi_NotUpdatable('\uea4f'),
		cbi_NoteIncluded('\uea87'),
		cbi_NoteOff('\uea86'),
		cbi_Notes('\ue91f'),
		cbi_NotesDoc('\uea42'),
		cbi_NotesFill('\ue9ce'),
		cbi_NotificationBig('\uea5a'),
		cbi_NotificationMini('\uea5b'),
		cbi_Number('\ueaaf'),
		cbi_OCR('\ue803'),
		cbi_ObscureArea('\ueac8'),
		cbi_Offline('\ue9bc'),
		cbi_OnAgreement('\uea25'),
		cbi_OpenedFolder('\ue63a'),
		cbi_Opening('\ueb85'),
		cbi_Or('\ue9f0'),
		cbi_OutGroup('\ue99d'),
		cbi_OutHotel('\ue765'),
		cbi_OutgoingCall('\uea61'),
		cbi_OutgoingCallNull('\uea8d'),
		cbi_OutgoingMail('\uea65'),
		cbi_Oval('\ue960'),
		cbi_PDF('\ue67c'),
		cbi_PF('\ueb34'),
		cbi_PUnanswered('\ue972'),
		cbi_Pacifier('\ue63b'),
		cbi_PacifierCross('\ueb05'),
		cbi_Pack('\ue6f6'),
		cbi_Pack2('\ue91c'),
		cbi_Pack3('\ueb1e'),
		cbi_Package('\uea96'),
		cbi_PageBreaks('\ue921'),
		cbi_PageNumber('\uea49'),
		cbi_PartiallyReady('\ue72c'),
		cbi_Paste('\ue6fd'),
		cbi_PasteAsText('\ue71e'),
		cbi_PasteBtr('\ue9a1'),
		cbi_PasteCodeBtr('\ue9a2'),
		cbi_PasteQuotesBtr('\ue9a0'),
		cbi_PasteStyle('\ue768'),
		cbi_PasteTextLetter('\ue6e7'),
		cbi_PatternsPoints('\ue91a'),
		cbi_Pause('\ue639'),
		cbi_Pause1('\ueae2'),
		cbi_Pay('\ueaa0'),
		cbi_Payment('\ue696'),
		cbi_PaymentCard('\ueaa2'),
		cbi_PaymentCardButton('\ueaa1'),
		cbi_PaymentCash('\ueaa4'),
		cbi_PaymentCashButton('\ueaa3'),
		cbi_PaymentPart('\ue695'),
		cbi_PaymentPart2('\uea2a'),
		cbi_PaymentPartSend('\uea06'),
		cbi_PaymentSalary('\ueaa6'),
		cbi_PaymentSalaryButton('\ueaa5'),
		cbi_Pencil('\ueac7'),
		cbi_Percent('\ueae7'),
		cbi_Perfume('\ueb06'),
		cbi_PermittedBuyers('\ue684'),
		cbi_PermittedGoods('\ue683'),
		cbi_PermittedRegions('\ue682'),
		cbi_Phone('\ue638'),
		cbi_PhoneCAM('\ue98f'),
		cbi_PhoneCell('\ue637'),
		cbi_PhoneCompany('\uea29'),
		cbi_PhoneContact('\ue978'),
		cbi_PhoneCrash('\ue966'),
		cbi_PhoneDial('\ueacc'),
		cbi_PhoneDown('\ue914'),
		cbi_PhoneFax('\ue977'),
		cbi_PhoneGetAutomatically('\ue624'),
		cbi_PhoneGetManually('\ue615'),
		cbi_PhoneHome('\ue976'),
		cbi_PhoneMes('\ue975'),
		cbi_PhoneMissed('\ue965'),
		cbi_PhoneNull('\ue636'),
		cbi_PhoneNumber('\ue974'),
		cbi_PhonePause('\ue973'),
		cbi_PhoneUnanswered('\ue964'),
		cbi_PhoneVariable('\ue971'),
		cbi_PhoneWWW('\ue990'),
		cbi_PhoneWork('\ue635'),
		cbi_Photo('\ue6ed'),
		cbi_PicBtr('\ue9a3'),
		cbi_PicCenter('\ue9ff'),
		cbi_PicInTheText('\uea53'),
		cbi_PicLeft('\ue9fe'),
		cbi_PicLeftT('\ue9fd'),
		cbi_PicOverTheText('\uea54'),
		cbi_PicRight('\ue9fc'),
		cbi_Picture('\ue6c9'),
		cbi_Pin('\ue630'),
		cbi_Pin2('\ue930'),
		cbi_PinCode('\ue9c4'),
		cbi_PinNull('\ue97c'),
		cbi_PinOff('\uea09'),
		cbi_Pipe('\ueb53'),
		cbi_PlayBack('\ueac0'),
		cbi_PlayForward('\ueabf'),
		cbi_PlaySound('\ue99c'),
		cbi_Plus('\uea48'),
		cbi_Plus2('\ueb64'),
		cbi_Preferment('\ue634'),
		cbi_Presto('\ue701'),
		cbi_Preview('\ueab3'),
		cbi_Price('\ue9d4'),
		cbi_Print('\ue633'),
		cbi_PrintForm('\ue9f8'),
		cbi_Processing('\ueb83'),
		cbi_ProductsDownload('\uea20'),
		cbi_Profile('\ue632'),
		cbi_Profile2('\ue91d'),
		cbi_Promokod('\ueb7d'),
		cbi_Property('\ue74d'),
		cbi_Publish2('\ue631'),
		cbi_Purchases('\uead9'),
		cbi_QR('\ue915'),
		cbi_Question('\ueb3c'),
		cbi_Question2('\ue68b'),
		cbi_QuestionNew('\ue9c9'),
		cbi_Queue('\ueb3d'),
		cbi_Quote('\ue6e8'),
		cbi_R('\ue9ed'),
		cbi_RPN('\ueb35'),
		cbi_RebuildWithDebugging('\ueb22'),
		cbi_Rec('\ue9da'),
		cbi_RecalculationOfPrices('\uea10'),
		cbi_Received('\ue62e'),
		cbi_Received2('\ue62d'),
		cbi_Rectangle('\ue94e'),
		cbi_Redirect('\ueae3'),
		cbi_Redo('\ue6a1'),
		cbi_Redo2('\ue6ca'),
		cbi_ReduceButton('\ue702'),
		cbi_Refresh('\ue62c'),
		cbi_RefusedAgency('\ue72e'),
		cbi_RefusedOperator('\ue72f'),
		cbi_RelatedDocumentsDown('\uea07'),
		cbi_RelatedDocumentsUp('\uea08'),
		cbi_Remark('\ue9be'),
		cbi_RemarkNull('\ue9bd'),
		cbi_RemoteConnection('\uead7'),
		cbi_RemoveAdd('\ue766'),
		cbi_Rename('\ue698'),
		cbi_Reply('\uea2e'),
		cbi_Report('\ue62b'),
		cbi_RequestScreen('\ueacf'),
		cbi_Resend('\ue62a'),
		cbi_Resources('\ue74e'),
		cbi_Responsible('\ue6f7'),
		cbi_Responsible2('\ue767'),
		cbi_Restore('\ue629'),
		cbi_Ring('\ueb78'),
		cbi_Roaming('\ue707'),
		cbi_Robot('\ueb74'),
		cbi_RoundPlus('\ueadd'),
		cbi_Ruble('\ue6a3'),
		cbi_RubleNone('\ue9cd'),
		cbi_Russian('\ueb86'),
		cbi_SAP('\ue904'),
		cbi_SJNon('\uea15'),
		cbi_STAT('\ueb37'),
		cbi_Saby('\ue98c'),
		cbi_SabyBird('\ue9e2'),
		cbi_SabyCloud('\ue9dd'),
		cbi_SabyDisk('\ue901'),
		cbi_SabyEng('\ue9e1'),
		cbi_Salary('\ue9e9'),
		cbi_Salepoint('\ueab2'),
		cbi_Sandclock('\ue68f'),
		cbi_Save('\ue628'),
		cbi_SaveAs('\ue627'),
		cbi_Scale('\ue94f'),
		cbi_ScaleOriginal('\ueacb'),
		cbi_Scan('\ue626'),
		cbi_ScanSave('\ue625'),
		cbi_Scanner('\uea00'),
		cbi_Scissors('\ue969'),
		cbi_ScrollToTop('\ueb75'),
		cbi_Search('\ue623'),
		cbi_Search2('\ue662'),
		cbi_Search3('\ueaa7'),
		cbi_Seen('\ue622'),
		cbi_SelectArea('\uea1e'),
		cbi_SelectGeotag('\ueb65'),
		cbi_SelfPin('\ue621'),
		cbi_SelfVacation('\ue620'),
		cbi_Sell('\ueaa8'),
		cbi_Send('\ue61f'),
		cbi_SendLetter('\ueb50'),
		cbi_Sent('\ue61e'),
		cbi_Sent2('\ue61d'),
		cbi_Sent3('\ue908'),
		cbi_SentBig('\ueaac'),
		cbi_SentNot('\uea63'),
		cbi_SentOff('\uead6'),
		cbi_ServerKey('\ue61c'),
		cbi_Service('\uea4e'),
		cbi_ServiceArrow('\uea5e'),
		cbi_ServiceDuble('\uea71'),
		cbi_Settings('\ue61b'),
		cbi_Settings2('\ueaa9'),
		cbi_SettingsNew('\ue9d9'),
		cbi_Shadow('\ue9a5'),
		cbi_Share('\ue61a'),
		cbi_Shield('\ueb76'),
		cbi_Ship('\ue9ca'),
		cbi_Shipment('\ue9f6'),
		cbi_ShipmentPartial('\ue9f7'),
		cbi_Shop('\uea5f'),
		cbi_ShortList('\ue962'),
		cbi_Show('\ue619'),
		cbi_ShowBig('\uea19'),
		cbi_ShowControl('\ue968'),
		cbi_Shteker('\uea58'),
		cbi_Sick('\ue618'),
		cbi_SickAuto('\ueb3e'),
		cbi_SignChange('\ueaea'),
		cbi_Signature('\ue68a'),
		cbi_SignatureBird('\uea85'),
		cbi_SignatureBirdNone('\uea84'),
		cbi_SignatureNone('\ue74a'),
		cbi_SignaturePhone('\ueb26'),
		cbi_SignaturePhoneNone('\ueb27'),
		cbi_Skeleton('\ue76d'),
		cbi_Skype('\ue617'),
		cbi_SmileBtr('\ue9a7'),
		cbi_Snow('\ue970'),
		cbi_SortByAmount('\uea97'),
		cbi_SortByDiv('\ueb3f'),
		cbi_SortByOrder('\ueb40'),
		cbi_Sorting('\ue909'),
		cbi_SortingEng('\ue9df'),
		cbi_SortingNumber('\uea66'),
		cbi_SortingStandard('\ueb66'),
		cbi_SoundMax('\ue90e'),
		cbi_SoundMidi('\ue910'),
		cbi_SoundMini('\ue911'),
		cbi_SoundOff('\ue912'),
		cbi_SoundOff1('\ueb67'),
		cbi_SoundOn('\ueb68'),
		cbi_Space('\uea33'),
		cbi_SplitCellHorizontally('\ueb13'),
		cbi_SplitCellVertically('\ueb10'),
		cbi_Square('\uea12'),
		cbi_SquareGeom('\ueb36'),
		cbi_Squarefilled('\uea13'),
		cbi_Statement('\uea7e'),
		cbi_Statistics('\ue91b'),
		cbi_Sticker('\ueb43'),
		cbi_Stroked('\ue6cb'),
		cbi_Subscribe('\ue9d2'),
		cbi_Subtraction('\ueae5'),
		cbi_Successful('\ue616'),
		cbi_Successful2('\ue92c'),
		cbi_SuccessfulDocument('\uea45'),
		cbi_SuccessfulNon('\ueab1'),
		cbi_Successfully('\uea46'),
		cbi_Sum('\ue614'),
		cbi_Superjob('\ue9ad'),
		cbi_Surveyor('\ue613'),
		cbi_Surveyors('\ue612'),
		cbi_SvMax('\uea40'),
		cbi_SvMini('\uea41'),
		cbi_SvNarrow('\uea3f'),
		cbi_SvWide('\uea3e'),
		cbi_SwipeMenu('\ueab4'),
		cbi_TFAdjustmentReport('\ue729'),
		cbi_TFAttach('\ue74f'),
		cbi_TFCloudKey('\ue750'),
		cbi_TFComputer('\ue730'),
		cbi_TFComputerCross('\ueb54'),
		cbi_TFComputerPlagin('\ueb55'),
		cbi_TFCurtailRTE('\ue751'),
		cbi_TFCurtailRTE2('\ue764'),
		cbi_TFDelete('\ue752'),
		cbi_TFDesktop('\ue731'),
		cbi_TFDialogue('\ue75c'),
		cbi_TFDocStamp('\uea8f'),
		cbi_TFDocument('\ue732'),
		cbi_TFDocumentINI('\ueaf9'),
		cbi_TFDocumentLnk('\ueb23'),
		cbi_TFDocumentMP4('\ue9cb'),
		cbi_TFDocumentNon('\ue9dc'),
		cbi_TFDocumentODS('\ue9cc'),
		cbi_TFDocumentP('\ue733'),
		cbi_TFDocumentPDF('\ue734'),
		cbi_TFDocumentPY('\ueafa'),
		cbi_TFDocumentSQL('\ueafb'),
		cbi_TFDocumentUnknownType('\ue735'),
		cbi_TFDocumentVsdx('\ue9d0'),
		cbi_TFDocumentW('\ue736'),
		cbi_TFDocumentX('\ue737'),
		cbi_TFDocumentXML('\ueab7'),
		cbi_TFDocumentXml('\ue738'),
		cbi_TFDownload('\ue739'),
		cbi_TFEmployees('\ue753'),
		cbi_TFExpand('\ue73a'),
		cbi_TFExpandRTE('\ue754'),
		cbi_TFFavorite('\ue73b'),
		cbi_TFFileAudio('\ue73c'),
		cbi_TFFileVideo('\ue73d'),
		cbi_TFFolder('\ue73e'),
		cbi_TFFolder2('\ue73f'),
		cbi_TFFolder2Opened('\ueb41'),
		cbi_TFFollow('\ue740'),
		cbi_TFForward('\ue755'),
		cbi_TFImage('\ue72a'),
		cbi_TFList('\ue741'),
		cbi_TFList2('\ue742'),
		cbi_TFLocalDrive('\ue743'),
		cbi_TFMessage('\ue756'),
		cbi_TFMyDocuments('\ue757'),
		cbi_TFNetwork('\ue744'),
		cbi_TFNetworkDrive('\ue745'),
		cbi_TFNewTab('\ue746'),
		cbi_TFPreview('\ue747'),
		cbi_TFPreview2('\ue748'),
		cbi_TFSettings('\ue75d'),
		cbi_TFTask('\ue758'),
		cbi_TFUSBDrive('\ue759'),
		cbi_TFUSBKey('\ue75a'),
		cbi_TFVideoMessage('\ue75b'),
		cbi_TFZip('\ue749'),
		cbi_TFlist3('\ueac3'),
		cbi_Table('\ue6cc'),
		cbi_TableAddLeft('\ue953'),
		cbi_TableAddRight('\ue952'),
		cbi_TableCell('\ueb0c'),
		cbi_TableColumn('\ueb0a'),
		cbi_TableCreate('\ue958'),
		cbi_TableDelete('\ue957'),
		cbi_TableDeleteCell('\ueb14'),
		cbi_TableDeleteColumn('\ue951'),
		cbi_TableDeleteRow('\ue954'),
		cbi_TableInsertAbove('\ue956'),
		cbi_TableInsertBelow('\ue955'),
		cbi_TableMoveAbove('\ueb12'),
		cbi_TableMoveBelow('\ueb0f'),
		cbi_TableMoveLeft('\ueb11'),
		cbi_TableMoveRight('\ueb0e'),
		cbi_TableRow('\ueb0b'),
		cbi_TableRowSettings('\ueb15'),
		cbi_TableScheme('\ueb5a'),
		cbi_TableSetting('\ue950'),
		cbi_Tag('\uea18'),
		cbi_TakePhoto('\ueb77'),
		cbi_Telecommunications('\ueb70'),
		cbi_Telegram('\uea03'),
		cbi_TelephoneNull('\uea8e'),
		cbi_TemplateNews1('\ue985'),
		cbi_TemplateNews2('\ue993'),
		cbi_TemplateNews3('\ue992'),
		cbi_TemplateNews4('\ue987'),
		cbi_TemplateNews5('\ue986'),
		cbi_TemplateNews6('\ue988'),
		cbi_TemplateNews7('\ue98b'),
		cbi_TemplateNews8('\ue98a'),
		cbi_TemplateNews9('\ue989'),
		cbi_Text('\ueac9'),
		cbi_TextColor('\ue6cd'),
		cbi_TextSettings('\ue761'),
		cbi_TheBordersBottom('\uead1'),
		cbi_TheBordersLeft('\uead4'),
		cbi_TheBordersOnTop('\uead3'),
		cbi_TheBordersRight('\uead2'),
		cbi_TheNote('\ue9d3'),
		cbi_ThreeColumns('\ueaed'),
		cbi_ThresholdConditions('\ue680'),
		cbi_ThumbDown('\ue611'),
		cbi_ThumbDown2('\ue610'),
		cbi_ThumbDownBig('\uea22'),
		cbi_ThumbUp('\ue60f'),
		cbi_ThumbUp2('\ue60e'),
		cbi_ThumbUpBig('\uea21'),
		cbi_ThumbUpPlus('\uea0c'),
		cbi_Time('\ue68d'),
		cbi_TimeHistory('\ue9c3'),
		cbi_TimeHistoryMirror('\uea1a'),
		cbi_TimeOK('\ue9ba'),
		cbi_TimeOff('\ue963'),
		cbi_TimeSkinny('\ueb5b'),
		cbi_Tires('\ueb07'),
		cbi_ToApprove('\uea24'),
		cbi_ToArchive('\ue697'),
		cbi_ToTheBegining('\uea0a'),
		cbi_Tobacco('\ueb08'),
		cbi_Trade('\ue60c'),
		cbi_Trade2('\ueb71'),
		cbi_TransitionFrom('\ue982'),
		cbi_TransitionTo('\ue983'),
		cbi_Trash_bucket('\ueb72'),
		cbi_TreeClosed('\uea8b'),
		cbi_TreeOpen('\uea8a'),
		cbi_TreeView('\ue60b'),
		cbi_TrendDown('\ue71c'),
		cbi_TrendUp('\ue71d'),
		cbi_Truck('\ue6a5'),
		cbi_Truck2('\ueb73'),
		cbi_TruckHalf('\ue690'),
		cbi_TurnL('\ue60a'),
		cbi_TurnList('\ue97a'),
		cbi_TurnR('\ue609'),
		cbi_TurnstileIn('\ue6f8'),
		cbi_TurnstileOut('\ue6f9'),
		cbi_TwoColumns('\ueaee'),
		cbi_TwoForOne('\ueb69'),
		cbi_TypeArray('\uea6d'),
		cbi_TypeBool('\uea6a'),
		cbi_TypeDate('\uea68'),
		cbi_TypeNum('\uea6c'),
		cbi_TypeObject('\uea6e'),
		cbi_TypeStr('\uea6b'),
		cbi_TypeVoid('\uea69'),
		cbi_UDS('\ueb24'),
		cbi_USBKey2('\ueab5'),
		cbi_UnFullScrin('\ue95e'),
		cbi_UnPublish('\ue62f'),
		cbi_UnSubscribe('\ue9d1'),
		cbi_Underline('\ue6ce'),
		cbi_Undo('\ue608'),
		cbi_Undo2('\ue6cf'),
		cbi_Unfavorite('\ue607'),
		cbi_Unite('\ue6fa'),
		cbi_Unlink('\ue6d0'),
		cbi_UnloadNew('\uea31'),
		cbi_Unlock('\ue606'),
		cbi_Unsuccess('\ue605'),
		cbi_Up('\ue997'),
		cbi_UpDown('\uea62'),
		cbi_Upload('\ue604'),
		cbi_UploadYourself('\uea6f'),
		cbi_UsbKey('\ue603'),
		cbi_UseCase('\ueb2a'),
		cbi_Vacation('\ue602'),
		cbi_VacationNull('\ue96a'),
		cbi_ValidityPeriod('\ue67f'),
		cbi_Vape('\ueb79'),
		cbi_Viber('\uea02'),
		cbi_VideoCall('\ue693'),
		cbi_VideoCall2('\ue929'),
		cbi_VideoCallIncoming('\ue69f'),
		cbi_VideoCallNull('\ue6a0'),
		cbi_VideoCallOff('\ue913'),
		cbi_VideoCallOutgoing('\ue69e'),
		cbi_VideoGroup('\ue98d'),
		cbi_VideoLink('\ue924'),
		cbi_VideoMessage('\ue6fc'),
		cbi_View('\ue6a2'),
		cbi_ViewBack('\ue789'),
		cbi_Vkrugu('\ue762'),
		cbi_VoiceMenu('\ue984'),
		cbi_WWW('\ue6d1'),
		cbi_WaitingSignature('\uea37'),
		cbi_Wallet('\ue601'),
		cbi_WaterSign('\uead8'),
		cbi_Way('\uea70'),
		cbi_Web('\ueb5c'),
		cbi_WebCamera('\ue6ee'),
		cbi_Webasyst('\ueaf1'),
		cbi_WeekBackward('\ue685'),
		cbi_WeekDown('\ue903'),
		cbi_WeekForward('\ue681'),
		cbi_WeekUp('\ue902'),
		cbi_WeigherOff('\ueadb'),
		cbi_WeigherOn('\ueada'),
		cbi_WhatsUp('\uea01'),
		cbi_Wheelchair('\ueb09'),
		cbi_Whiteboard('\ueabd'),
		cbi_Wi('\ue6a6'),
		cbi_WiFi('\ue600'),
		cbi_WidgetShop('\uea91'),
		cbi_Work('\ue9e8'),
		cbi_WorkForAll('\uea1c'),
		cbi_WorkInFocus('\ue67e'),
		cbi_WorkRead('\ue6eb'),
		cbi_WorkRussia('\ueb6a'),
		cbi_Workers('\ueaaa'),
		cbi_Writemessage('\ueb5f'),
		cbi_Yandex('\uea4b'),
		cbi_YandexEda('\ueb5d'),
		cbi_Yes('\ue75e'),
		cbi_You('\ue6fe'),
		cbi_Youtube('\ueaab'),
		cbi_ZodiacSignAquarius('\ue709'),
		cbi_ZodiacSignAries('\ue70a'),
		cbi_ZodiacSignCancer('\ue70b'),
		cbi_ZodiacSignCapricorn('\ue70c'),
		cbi_ZodiacSignGemini('\ue70d'),
		cbi_ZodiacSignLeo('\ue70e'),
		cbi_ZodiacSignLibra('\ue70f'),
		cbi_ZodiacSignPisces('\ue710'),
		cbi_ZodiacSignSagittarius('\ue711'),
		cbi_ZodiacSignScorpio('\ue712'),
		cbi_ZodiacSignTaurus('\ue713'),
		cbi_ZodiacSignVirgo('\ue714'),
		cbi_ZoomIn('\ue6e9'),
		cbi_ZoomOut('\ue6ea'),
		cbi_eye('\ueab9'),
		cbi_folderClosedMin('\ueb8b'),
		cbi_folderOpenMin('\ueb8c'),
		cbi_gasStation('\uea17'),
		cbi_iOS('\ue76a'),
		cbi_insertCellAfter('\ue9b6'),
		cbi_insertCellBefore('\ue9b5'),
		cbi_insertRowNumber('\ue9b8'),
		cbi_insertTable('\ue9b9'),
		cbi_mergeCells('\ue9b2'),
		cbi_osChrome('\ueb46'),
		cbi_osFirefox('\ueb47'),
		cbi_osJava('\ueb48'),
		cbi_osLinux('\ueb4a'),
		cbi_osMac('\ueb4b'),
		cbi_osWindows('\ueb4c'),
		cbi_pAlignCenter('\uea7a'),
		cbi_pAlignLeft('\uea76'),
		cbi_pAlignRight('\uea7b'),
		cbi_pBringToFront('\uea7d'),
		cbi_pGrid('\uea80'),
		cbi_pSendToBack('\uea7c'),
		cbi_pTable('\uea77'),
		cbi_pToPave('\uea78'),
		cbi_pToStretch('\uea79'),
		cbi_removeCell('\ue9b7'),
		cbi_separateHorizontal('\ue9b4'),
		cbi_separateVertical('\ue9b3'),
		cbi_statusAffairs('\ue940'),
		cbi_statusCars('\ue945'),
		cbi_statusCatches('\ue935'),
		cbi_statusCaution('\ue943'),
		cbi_statusCoffee('\ue936'),
		cbi_statusConnected('\ue94a'),
		cbi_statusConsultant('\ue942'),
		cbi_statusDeparted('\ue94b'),
		cbi_statusDictates('\ue93c'),
		cbi_statusDisease('\ue93b'),
		cbi_statusDisturb('\ue949'),
		cbi_statusDraws('\ue932'),
		cbi_statusDrips('\ue944'),
		cbi_statusFarmer('\ue933'),
		cbi_statusGymnast('\ue931'),
		cbi_statusMeditation('\ue941'),
		cbi_statusPlan('\ue93f'),
		cbi_statusPresident('\ue93a'),
		cbi_statusPromenade('\ue938'),
		cbi_statusSleeps('\ue93e'),
		cbi_statusSun('\ue937'),
		cbi_statusTable('\ue93d'),
		cbi_statusThinks('\ue934'),
		cbi_statusTime('\ue939');

        /**
         * Префикс шрифта 'cbuc-icons'.
         */
        @SuppressWarnings("unused")
        public static final String PREFIX = "cbi_";

        char character;

        Icon(char character) {
            this.character = character;
        }

        /**
         * Метод для получения имени иконки обернутого в фигурные кавычки '{' и '}'.
         */
        public String getFormattedName() {
            return "{" + name() + "}";
        }

        /**
         * Метод для получения иконки.
         */
        public char getCharacter() {
            return character;
        }

        /**
         * Метод для получения имени иконки.
         */
        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static ITypeface typeface;

        /** @SelfDocumented */
        public ITypeface getTypeface() {
            if (typeface == null) {
                typeface = new CbucIcon();
            }
            return typeface;
        }

        /** @SelfDocumented */
        @SuppressWarnings("unused")
        @NonNull
        public static Icon parseString(@Nullable String name, Icon defaultValue) {
            Icon icon = parseString(name);
            return icon == null ? defaultValue : icon;
        }

        /** @SelfDocumented */
        @Nullable
        public static Icon parseString(@Nullable String name) {
            if (name == null) {
                return null;
            }
            Icon result;
            try {
                result = Icon.valueOf(name);
            } catch (IllegalArgumentException e) {
                Timber.d(e);
                result = null;
            }
            return result;
        }

    }
}
